version: '2.1'

services:
  app:
    build: .
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
      - AMQP_QUEUE=aws.ses.mailer
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=AKID
      - AWS_SECRET_ACCESS_KEY=SECRET
      - AWS_S3_BUCKET=bucket
      - AWS_VERIFIED_FROM_EMAIL_ADDRESS=info@veloxbox.us
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 0.0.0.0:15672:15672  # management utility